// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Products List",
            "schema": {
              "$ref": "#/definitions/ProductsList"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product is found",
            "schema": {
              "$ref": "#/definitions/AvaliableProduct"
            }
          },
          "404": {
            "description": "Product is not found"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductInterface": {
      "properties": {
        "description": {
          "$ref": "#/definitions/String",
          "title": "ProductInterface.description"
        },
        "id": {
          "$ref": "#/definitions/String",
          "title": "ProductInterface.id"
        },
        "price": {
          "title": "ProductInterface.price",
          "type": "number"
        },
        "title": {
          "$ref": "#/definitions/String",
          "title": "ProductInterface.title"
        }
      },
      "required": [
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "ProductInterface",
      "type": "object"
    },
    "Product": {
      "$ref": "#/definitions/ProductInterface",
      "title": "Product"
    },
    "AvaliableProduct": {
      "allOf": [
        {
          "$ref": "#/definitions/ProductInterface"
        },
        {
          "properties": {
            "count": {
              "title": "count",
              "type": "number"
            }
          },
          "additionalProperties": false,
          "type": "object"
        }
      ],
      "title": "AvaliableProduct"
    },
    "ProductsList": {
      "items": {
        "$ref": "#/definitions/AvaliableProduct"
      },
      "title": "ProductsList",
      "type": "array"
    }
  },
  "securityDefinitions": {},
  "host": "xuohj4pat5.execute-api.eu-central-1.amazonaws.com/dev"
};